<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Data Transfers', description: 'Asynchronous CSV and XLSX import and export orchestration')]
#[OA\Get(path: '/api/data-transfers/types', operationId: 'listDataTransferTypes', summary: 'List registered import and export handlers', security: [['bearerAuth' => []]], tags: ['Data Transfers'], responses: [new OA\Response(response: 200, description: 'Registered types, formats, and columns', content: new OA\JsonContent(type: 'object', example: ['success' => true, 'data' => ['types' => [['key' => 'identity.users', 'label' => 'Identity users', 'import' => true, 'export' => true, 'formats' => ['csv', 'xlsx'], 'columns' => ['name', 'email'], 'import_columns' => ['name', 'email', 'status', 'locale']]]]])), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Get(path: '/api/data-transfers', operationId: 'listDataTransfers', summary: 'List owned data transfers using cursor pagination', security: [['bearerAuth' => []]], tags: ['Data Transfers'], parameters: [new OA\Parameter(name: 'direction', in: 'query', schema: new OA\Schema(type: 'string', enum: ['import', 'export'])), new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['pending', 'processing', 'completed', 'failed', 'cancelled'])), new OA\Parameter(name: 'type', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100)), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Cursor paginated transfers', content: new OA\JsonContent(ref: '#/components/schemas/DataTransferCollectionResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/data-transfers/exports', operationId: 'createDataExport', summary: 'Queue a CSV or XLSX export', description: 'Set format to csv or xlsx. Requires data-transfers.create and Idempotency-Key. The output_file_id becomes available after completion and can be downloaded through the Files API.', security: [['bearerAuth' => []]], tags: ['Data Transfers'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreateDataExportRequest')), responses: [new OA\Response(response: 202, description: 'Export queued', content: new OA\JsonContent(ref: '#/components/schemas/DataTransferResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Missing permission', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Invalid type, format, or request', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
#[OA\Post(path: '/api/data-transfers/imports', operationId: 'createDataImport', summary: 'Queue a CSV or XLSX import', description: 'Upload the CSV or XLSX through POST /api/files first, then provide its public file ID. The format is detected from the stored file. Requires data-transfers.create and Idempotency-Key.', security: [['bearerAuth' => []]], tags: ['Data Transfers'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreateDataImportRequest')), responses: [new OA\Response(response: 202, description: 'Import queued', content: new OA\JsonContent(ref: '#/components/schemas/DataTransferResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Missing permission', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Invalid type, file, or request', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
#[OA\Get(path: '/api/data-transfers/{dataTransfer}', operationId: 'showDataTransfer', summary: 'Show transfer progress and result', security: [['bearerAuth' => []]], tags: ['Data Transfers'], parameters: [new OA\Parameter(name: 'dataTransfer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Transfer state', content: new OA\JsonContent(ref: '#/components/schemas/DataTransferResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Unavailable transfer', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/data-transfers/{dataTransfer}/cancel', operationId: 'cancelDataTransfer', summary: 'Cancel a pending or processing transfer', security: [['bearerAuth' => []]], tags: ['Data Transfers'], parameters: [new OA\Parameter(name: 'dataTransfer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Transfer cancelled', content: new OA\JsonContent(ref: '#/components/schemas/DataTransferResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Unavailable transfer', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Transfer is already terminal', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Schema(schema: 'CreateDataExportRequest', required: ['type'], properties: [new OA\Property(property: 'type', type: 'string', example: 'identity.users'), new OA\Property(property: 'format', description: 'Defaults to csv.', type: 'string', enum: ['csv', 'xlsx'], example: 'xlsx'), new OA\Property(property: 'options', type: 'object', example: [])], type: 'object')]
#[OA\Schema(schema: 'CreateDataImportRequest', required: ['type', 'file_id'], properties: [new OA\Property(property: 'type', type: 'string', example: 'identity.users'), new OA\Property(property: 'file_id', description: 'Public UUID returned by POST /api/files.', type: 'string', format: 'uuid'), new OA\Property(property: 'options', type: 'object', example: [])], type: 'object')]
#[OA\Schema(schema: 'DataTransfer', required: ['id', 'type', 'direction', 'format', 'status', 'progress', 'errors', 'created_at', 'updated_at'], properties: [new OA\Property(property: 'id', type: 'string', format: 'uuid'), new OA\Property(property: 'type', type: 'string', example: 'identity.users'), new OA\Property(property: 'direction', type: 'string', enum: ['import', 'export']), new OA\Property(property: 'format', type: 'string', enum: ['csv', 'xlsx']), new OA\Property(property: 'status', type: 'string', enum: ['pending', 'processing', 'completed', 'failed', 'cancelled']), new OA\Property(property: 'progress', properties: [new OA\Property(property: 'total_rows', type: ['integer', 'null']), new OA\Property(property: 'processed_rows', type: 'integer'), new OA\Property(property: 'successful_rows', type: 'integer'), new OA\Property(property: 'failed_rows', type: 'integer')], type: 'object'), new OA\Property(property: 'input_file_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'output_file_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'errors', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'failure_message', type: ['string', 'null']), new OA\Property(property: 'started_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'finished_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'created_at', type: 'string', format: 'date-time'), new OA\Property(property: 'updated_at', type: 'string', format: 'date-time')], type: 'object')]
#[OA\Schema(schema: 'DataTransferResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', ref: '#/components/schemas/DataTransfer')], type: 'object')]
#[OA\Schema(schema: 'DataTransferCollectionResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/DataTransfer')), new OA\Property(property: 'next_cursor', type: ['string', 'null']), new OA\Property(property: 'prev_cursor', type: ['string', 'null']), new OA\Property(property: 'per_page', type: 'integer')], type: 'object')], type: 'object')]
final class DataTransferSpec {}
