<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'HealthResponse', type: 'object', example: ['status' => 'healthy', 'services' => ['database' => ['status' => 'up', 'required' => true], 'redis' => ['status' => 'up', 'required' => true], 'storage' => ['status' => 'up', 'required' => false], 'ai' => ['status' => 'not_configured', 'required' => false]]])]
#[OA\Schema(schema: 'LocalesResponse', type: 'object', example: ['success' => true, 'data' => ['supported' => [['code' => 'en', 'name' => 'English'], ['code' => 'id', 'name' => 'Bahasa Indonesia']], 'default' => 'en', 'fallback' => 'en']])]
#[OA\Schema(schema: 'PermissionListResponse', type: 'object', example: ['success' => true, 'data' => [['id' => 1, 'name' => 'users.view'], ['id' => 2, 'name' => 'roles.view']]])]
#[OA\Schema(schema: 'RoleResponse', type: 'object', example: ['success' => true, 'data' => ['id' => 2, 'name' => 'admin', 'guard_name' => 'web', 'created_at' => '2026-09-28T08:00:00Z', 'updated_at' => '2026-09-28T08:00:00Z', 'permissions' => [['id' => 1, 'name' => 'users.view'], ['id' => 2, 'name' => 'roles.view']]]])]
#[OA\Schema(schema: 'RoleListResponse', type: 'object', example: ['success' => true, 'data' => [['id' => 2, 'name' => 'admin', 'guard_name' => 'web', 'created_at' => '2026-09-28T08:00:00Z', 'updated_at' => '2026-09-28T08:00:00Z', 'permissions' => [['id' => 1, 'name' => 'users.view']]]]])]
#[OA\Schema(schema: 'UserDetailResponse', type: 'object', example: ['success' => true, 'data' => ['id' => 1, 'name' => 'Administrator', 'email' => 'admin@example.com', 'status' => 'active', 'locale' => 'en', 'email_verified_at' => '2026-09-28T08:00:00Z', 'last_login_at' => '2026-09-28T08:05:00Z', 'roles' => [['id' => 1, 'name' => 'super-admin']], 'permissions' => ['users.view', 'roles.view'], 'active_tokens' => 1]])]
#[OA\Schema(schema: 'UserStatusResponse', type: 'object', example: ['success' => true, 'data' => ['id' => 2, 'name' => 'Operator', 'email' => 'operator@example.com', 'status' => 'suspended', 'locale' => 'id', 'email_verified_at' => '2026-09-28T08:00:00Z', 'last_login_at' => null]])]
#[OA\Schema(schema: 'UserRolesResponse', type: 'object', example: ['success' => true, 'data' => ['roles' => ['admin', 'user']]])]
#[OA\Schema(schema: 'PublicSettingsResponse', type: 'object', example: ['success' => true, 'data' => ['app.name' => 'Core R', 'app.locale' => 'en', 'app.timezone' => 'Asia/Jakarta', 'auth.registration_enabled' => false, 'auth.email_verification_required' => true]])]
#[OA\Schema(schema: 'SettingsResponse', type: 'object', example: ['success' => true, 'data' => ['app.name' => 'Core R', 'app.locale' => 'en', 'app.timezone' => 'Asia/Jakarta', 'auth.registration_enabled' => false, 'auth.email_verification_required' => true, 'auth.token_expiration_days' => 30, 'auth.max_login_attempts' => 5, 'files.max_upload_mb' => 10, 'files.allowed_mime_types' => ['application/pdf', 'image/jpeg'], 'realtime.event_retention_days' => 7]])]
#[OA\Schema(schema: 'NotificationItem', type: 'object', example: ['id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'category' => 'security', 'title' => 'New login', 'message' => 'A new device signed in to your account.', 'action' => ['type' => 'open_url', 'url' => '/security/sessions'], 'context' => ['device_name' => 'Swagger UI'], 'read_at' => null, 'created_at' => '2026-09-28T08:00:00Z'])]
#[OA\Schema(schema: 'NotificationResponse', type: 'object', example: ['success' => true, 'data' => ['id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'category' => 'security', 'title' => 'New login', 'message' => 'A new device signed in to your account.', 'action' => ['type' => 'open_url', 'url' => '/security/sessions'], 'context' => ['device_name' => 'Swagger UI'], 'read_at' => null, 'created_at' => '2026-09-28T08:00:00Z']])]
#[OA\Schema(schema: 'NotificationListResponse', type: 'object', example: ['success' => true, 'data' => ['data' => [['id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'category' => 'security', 'title' => 'New login', 'message' => 'A new device signed in to your account.', 'action' => null, 'context' => [], 'read_at' => null, 'created_at' => '2026-09-28T08:00:00Z']], 'path' => 'https://core-r.p85.test:8443/api/notifications', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]
#[OA\Schema(schema: 'UnreadCountResponse', type: 'object', example: ['success' => true, 'data' => ['count' => 3]])]
#[OA\Schema(schema: 'NotificationPreferencesResponse', type: 'object', example: ['success' => true, 'data' => [['category' => 'security', 'database_enabled' => true, 'mail_enabled' => true, 'locked_channels' => ['database']], ['category' => 'account', 'database_enabled' => true, 'mail_enabled' => true, 'locked_channels' => []], ['category' => 'system', 'database_enabled' => true, 'mail_enabled' => false, 'locked_channels' => []]]])]
#[OA\Schema(schema: 'EventCursorResponse', type: 'object', example: ['success' => true, 'data' => ['cursor' => 'eyJpdiI6Ik9QQVFVRV9DVVJTT1IuLi4iLCJ2YWx1ZSI6Ii4uLiJ9']])]
#[OA\Schema(schema: 'BroadcastAuthorizationResponse', type: 'object', example: ['auth' => 'test-key:generated-hmac-signature'])]
final class DomainResponseSchemas {}
