<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Files', description: 'Private file storage and metadata')]
#[OA\Get(path: '/api/files', operationId: 'listFiles', summary: 'List files owned by the authenticated user', security: [['bearerAuth' => []]], tags: ['Files'], parameters: [new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'mime_type', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', default: 20, minimum: 1, maximum: 100))], responses: [new OA\Response(response: 200, description: 'Cursor-paginated owned files', content: new OA\JsonContent(ref: '#/components/schemas/FilesCursorResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/files', operationId: 'uploadFile', summary: 'Upload a private file', security: [['bearerAuth' => []]], tags: ['Files'], requestBody: new OA\RequestBody(required: true, content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(required: ['file'], properties: [new OA\Property(property: 'file', type: 'string', format: 'binary'), new OA\Property(property: 'display_name', type: 'string', maxLength: 255), new OA\Property(property: 'metadata', type: 'object', additionalProperties: new OA\AdditionalProperties)], type: 'object'))), responses: [new OA\Response(response: 201, description: 'File uploaded', content: new OA\JsonContent(ref: '#/components/schemas/FileSuccessResponse')), new OA\Response(response: 422, description: 'Invalid size, MIME type, name, or metadata', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
#[OA\Get(path: '/api/files/{file}', operationId: 'showFile', summary: 'Show private file metadata', security: [['bearerAuth' => []]], tags: ['Files'], parameters: [new OA\Parameter(name: 'file', description: 'Public file UUID', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'File metadata', content: new OA\JsonContent(ref: '#/components/schemas/FileSuccessResponse')), new OA\Response(response: 404, description: 'File unavailable or not authorized', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Patch(path: '/api/files/{file}', operationId: 'updateFile', summary: 'Update display name or safe metadata', security: [['bearerAuth' => []]], tags: ['Files'], parameters: [new OA\Parameter(name: 'file', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(properties: [new OA\Property(property: 'display_name', type: 'string', maxLength: 255), new OA\Property(property: 'metadata', type: ['object', 'null'])], type: 'object')), responses: [new OA\Response(response: 200, description: 'File updated', content: new OA\JsonContent(ref: '#/components/schemas/FileSuccessResponse')), new OA\Response(response: 404, description: 'File unavailable or not authorized', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
#[OA\Get(path: '/api/files/{file}/download', operationId: 'downloadFile', summary: 'Download authorized private file content', security: [['bearerAuth' => []]], tags: ['Files'], parameters: [new OA\Parameter(name: 'file', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Binary file', content: new OA\MediaType(mediaType: 'application/octet-stream', schema: new OA\Schema(type: 'string', format: 'binary'))), new OA\Response(response: 404, description: 'File unavailable or not authorized', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Delete(path: '/api/files/{file}', operationId: 'deleteFile', summary: 'Soft delete metadata and queue physical cleanup', security: [['bearerAuth' => []]], tags: ['Files'], parameters: [new OA\Parameter(name: 'file', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Deletion scheduled', content: new OA\JsonContent(ref: '#/components/schemas/MessageSuccessResponse')), new OA\Response(response: 404, description: 'File unavailable or not authorized', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'File is still attached', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Schema(schema: 'StoredFile', required: ['id', 'original_name', 'display_name', 'mime_type', 'size', 'visibility', 'created_at', 'updated_at'], properties: [new OA\Property(property: 'id', type: 'string', format: 'uuid'), new OA\Property(property: 'original_name', type: 'string', example: 'report.pdf'), new OA\Property(property: 'display_name', type: 'string', example: 'Quarterly Report.pdf'), new OA\Property(property: 'mime_type', type: 'string', example: 'application/pdf'), new OA\Property(property: 'extension', type: ['string', 'null'], example: 'pdf'), new OA\Property(property: 'size', description: 'File size in bytes', type: 'integer', format: 'int64', example: 24576), new OA\Property(property: 'visibility', type: 'string', enum: ['private'], example: 'private'), new OA\Property(property: 'metadata', type: ['object', 'null']), new OA\Property(property: 'attachments_count', type: 'integer', example: 0), new OA\Property(property: 'created_at', type: 'string', format: 'date-time'), new OA\Property(property: 'updated_at', type: 'string', format: 'date-time')], type: 'object')]
#[OA\Schema(schema: 'FileSuccessResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', ref: '#/components/schemas/StoredFile')], type: 'object')]
#[OA\Schema(schema: 'FilesCursorResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', description: 'Cursor paginator containing StoredFile records.', type: 'object')], type: 'object')]
final class FileSpec {}
