<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Notifications', description: 'Localized in-app notification inbox and channel preferences')]
#[OA\Get(path: '/api/notifications', operationId: 'listNotifications', summary: 'List the current user notification inbox', security: [['bearerAuth' => []]], tags: ['Notifications'], parameters: [new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['read', 'unread'])), new OA\Parameter(name: 'category', in: 'query', schema: new OA\Schema(type: 'string', enum: ['security', 'account', 'system'])), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', default: 20, minimum: 1, maximum: 100))], responses: [new OA\Response(response: 200, description: 'Cursor-paginated notifications', content: new OA\JsonContent(ref: '#/components/schemas/NotificationListResponse'))])]
#[OA\Get(path: '/api/notifications/unread-count', operationId: 'notificationUnreadCount', summary: 'Count unread notifications', security: [['bearerAuth' => []]], tags: ['Notifications'], responses: [new OA\Response(response: 200, description: 'Unread count', content: new OA\JsonContent(ref: '#/components/schemas/UnreadCountResponse'))])]
#[OA\Get(path: '/api/notifications/{notification}', operationId: 'showNotification', summary: 'Show an owned notification', security: [['bearerAuth' => []]], tags: ['Notifications'], parameters: [new OA\Parameter(name: 'notification', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Notification detail', content: new OA\JsonContent(ref: '#/components/schemas/NotificationResponse')), new OA\Response(response: 404, description: 'Unavailable or not owned', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Patch(path: '/api/notifications/{notification}/read', operationId: 'readNotification', summary: 'Mark an owned notification as read', security: [['bearerAuth' => []]], tags: ['Notifications'], parameters: [new OA\Parameter(name: 'notification', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Marked as read', content: new OA\JsonContent(ref: '#/components/schemas/NotificationResponse'))])]
#[OA\Delete(path: '/api/notifications/{notification}/read', operationId: 'unreadNotification', summary: 'Mark an owned notification as unread', security: [['bearerAuth' => []]], tags: ['Notifications'], parameters: [new OA\Parameter(name: 'notification', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Marked as unread', content: new OA\JsonContent(ref: '#/components/schemas/NotificationResponse'))])]
#[OA\Post(path: '/api/notifications/read-all', operationId: 'readAllNotifications', summary: 'Mark all owned notifications as read', security: [['bearerAuth' => []]], tags: ['Notifications'], responses: [new OA\Response(response: 200, description: 'All marked as read', content: new OA\JsonContent(ref: '#/components/schemas/MessageSuccessResponse'))])]
#[OA\Delete(path: '/api/notifications/{notification}', operationId: 'deleteNotification', summary: 'Delete an owned notification', security: [['bearerAuth' => []]], tags: ['Notifications'], parameters: [new OA\Parameter(name: 'notification', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Notification deleted', content: new OA\JsonContent(ref: '#/components/schemas/MessageSuccessResponse'))])]
#[OA\Get(path: '/api/notification-preferences', operationId: 'listNotificationPreferences', summary: 'List effective notification preferences', security: [['bearerAuth' => []]], tags: ['Notifications'], responses: [new OA\Response(response: 200, description: 'Effective preferences', content: new OA\JsonContent(ref: '#/components/schemas/NotificationPreferencesResponse'))])]
#[OA\Put(path: '/api/notification-preferences', operationId: 'updateNotificationPreferences', summary: 'Update notification channels per category', security: [['bearerAuth' => []]], tags: ['Notifications'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(properties: [new OA\Property(property: 'preferences', type: 'array', items: new OA\Items(properties: [new OA\Property(property: 'category', type: 'string', enum: ['security', 'account', 'system']), new OA\Property(property: 'database_enabled', type: 'boolean'), new OA\Property(property: 'mail_enabled', type: 'boolean')], type: 'object'))], type: 'object')), responses: [new OA\Response(response: 200, description: 'Preferences updated', content: new OA\JsonContent(ref: '#/components/schemas/NotificationPreferencesResponse')), new OA\Response(response: 422, description: 'Required channel cannot be disabled', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
final class NotificationSpec {}
