<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Payments', description: 'Provider-neutral payment state and Midtrans notification endpoint')]
#[OA\Get(path: '/api/payments/{payment}', operationId: 'showPayment', summary: 'Show a payment owned by the authenticated user', security: [['bearerAuth' => []]], tags: ['Payments'], parameters: [new OA\Parameter(name: 'payment', description: 'Public payment UUID', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Payment state and checkout URL', content: new OA\JsonContent(ref: '#/components/schemas/PaymentResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Payment unavailable or not owned', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/payments/webhooks/midtrans', operationId: 'receiveMidtransNotification', summary: 'Receive a signed Midtrans transaction notification', description: 'Called by Midtrans. The server verifies signature_key and the original amount, then processes duplicate notifications idempotently.', tags: ['Payments'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/MidtransNotificationRequest')), responses: [new OA\Response(response: 200, description: 'Notification accepted, including duplicate delivery', content: new OA\JsonContent(ref: '#/components/schemas/WebhookAcceptedResponse')), new OA\Response(response: 401, description: 'Invalid Midtrans signature', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Unknown provider order ID', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Invalid payload or amount mismatch', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
#[OA\Schema(schema: 'MidtransNotificationRequest', required: ['order_id', 'status_code', 'gross_amount', 'signature_key', 'transaction_status'], properties: [new OA\Property(property: 'order_id', type: 'string', example: 'CORE-0199a4e7-3f20-7b31-a592-1ed567ba84f1'), new OA\Property(property: 'transaction_id', type: 'string', example: '57d5293c-e65f-4a29-95e4-5959c3fa335b'), new OA\Property(property: 'transaction_status', type: 'string', enum: ['pending', 'authorize', 'capture', 'settlement', 'deny', 'cancel', 'expire', 'failure', 'refund', 'partial_refund', 'chargeback', 'partial_chargeback']), new OA\Property(property: 'status_code', type: 'string', example: '200'), new OA\Property(property: 'gross_amount', type: 'string', example: '125000.00'), new OA\Property(property: 'signature_key', type: 'string', example: 'sha512-signature-from-midtrans'), new OA\Property(property: 'payment_type', type: 'string', example: 'bank_transfer'), new OA\Property(property: 'fraud_status', type: 'string', example: 'accept')], type: 'object')]
#[OA\Schema(schema: 'Payment', required: ['id', 'provider', 'reference', 'amount', 'currency', 'status', 'created_at', 'updated_at'], properties: [new OA\Property(property: 'id', type: 'string', format: 'uuid'), new OA\Property(property: 'provider', type: 'string', example: 'midtrans'), new OA\Property(property: 'reference', properties: [new OA\Property(property: 'type', type: 'string', example: 'billing.invoice'), new OA\Property(property: 'id', type: 'string', example: 'INV-1001')], type: 'object'), new OA\Property(property: 'amount', description: 'Amount in the currency minor unit; IDR has no decimal fraction.', type: 'integer', example: 125000), new OA\Property(property: 'currency', type: 'string', example: 'IDR'), new OA\Property(property: 'status', type: 'string', enum: ['creating', 'pending', 'authorized', 'paid', 'denied', 'cancelled', 'expired', 'failed', 'provider_unknown', 'refunded', 'partially_refunded', 'chargeback', 'partial_chargeback']), new OA\Property(property: 'payment_type', type: ['string', 'null']), new OA\Property(property: 'checkout_url', type: ['string', 'null'], format: 'uri'), new OA\Property(property: 'paid_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'expires_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'created_at', type: 'string', format: 'date-time'), new OA\Property(property: 'updated_at', type: 'string', format: 'date-time')], type: 'object')]
#[OA\Schema(schema: 'PaymentResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', ref: '#/components/schemas/Payment')], type: 'object')]
#[OA\Schema(schema: 'WebhookAcceptedResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', required: ['received'], properties: [new OA\Property(property: 'received', type: 'boolean', example: true)], type: 'object')], type: 'object')]
final class PaymentSpec {}
