<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Realtime', description: 'Durable event synchronization with optional WebSocket delivery')]
#[OA\Schema(schema: 'UserEventResource', properties: [new OA\Property(property: 'type', type: 'string', example: 'notification'), new OA\Property(property: 'id', type: 'string', example: '0199f135-2500-7000-8000-000000000001')], type: 'object', nullable: true)]
#[OA\Schema(schema: 'UserEvent', required: ['id', 'type', 'schema_version', 'resource', 'payload', 'created_at'], properties: [new OA\Property(property: 'id', type: 'string', example: '01K5Y6RAV4QNZAVKF1K3Y3SME3'), new OA\Property(property: 'type', type: 'string', example: 'notification.created'), new OA\Property(property: 'schema_version', type: 'integer', example: 1), new OA\Property(property: 'resource', ref: '#/components/schemas/UserEventResource'), new OA\Property(property: 'payload', type: 'object', example: ['notification_id' => '0199f135-2500-7000-8000-000000000001', 'category' => 'security']), new OA\Property(property: 'created_at', type: 'string', format: 'date-time')], type: 'object')]
#[OA\Get(path: '/api/events', operationId: 'pollEvents', summary: 'Poll durable events after a cursor', description: 'Returns events in ascending order. Store next_cursor only after processing the full response. A 409 response means the cursor exceeded retention and the client must refresh its resources before requesting a new cursor.', security: [['bearerAuth' => []]], tags: ['Realtime'], parameters: [new OA\Parameter(name: 'cursor', description: 'Opaque cursor returned by this API', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'types[]', description: 'Optional event type filter; repeat the parameter for multiple types', in: 'query', schema: new OA\Schema(type: 'array', items: new OA\Items(type: 'string'))), new OA\Parameter(name: 'limit', in: 'query', schema: new OA\Schema(type: 'integer', default: 50, minimum: 1, maximum: 100))], responses: [new OA\Response(response: 200, description: 'Ordered event batch and next cursor', content: new OA\JsonContent(properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', properties: [new OA\Property(property: 'events', type: 'array', items: new OA\Items(ref: '#/components/schemas/UserEvent')), new OA\Property(property: 'next_cursor', type: 'string', nullable: true)], type: 'object')], type: 'object')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ApiError')), new OA\Response(response: 409, description: 'Cursor expired; refresh resources and obtain a new cursor', content: new OA\JsonContent(ref: '#/components/schemas/ApiError')), new OA\Response(response: 422, description: 'Invalid cursor or filters', content: new OA\JsonContent(ref: '#/components/schemas/ValidationErrorResponse'))])]
#[OA\Get(path: '/api/events/cursor', operationId: 'currentEventCursor', summary: 'Get a cursor at the current event boundary', security: [['bearerAuth' => []]], tags: ['Realtime'], responses: [new OA\Response(response: 200, description: 'Current opaque cursor, or null when no events exist', content: new OA\JsonContent(ref: '#/components/schemas/EventCursorResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ApiError'))])]
#[OA\Post(path: '/api/broadcasting/auth', operationId: 'authorizeBroadcastChannel', summary: 'Authorize a private WebSocket channel', description: 'Use a Sanctum bearer token. A user may only subscribe to users.{their_user_id}.', security: [['bearerAuth' => []]], tags: ['Realtime'], requestBody: new OA\RequestBody(required: true, content: new OA\MediaType(mediaType: 'application/x-www-form-urlencoded', schema: new OA\Schema(required: ['socket_id', 'channel_name'], properties: [new OA\Property(property: 'socket_id', type: 'string', example: '1234.5678'), new OA\Property(property: 'channel_name', type: 'string', example: 'private-users.42')], type: 'object'))), responses: [new OA\Response(response: 200, description: 'Channel authorization signature', content: new OA\JsonContent(ref: '#/components/schemas/BroadcastAuthorizationResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ApiError')), new OA\Response(response: 403, description: 'Channel does not belong to the user', content: new OA\JsonContent(ref: '#/components/schemas/ApiError'))])]
final class RealtimeSpec {}
