<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'RegisterRequest', required: ['name', 'email', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'name', type: 'string', example: 'Jane Doe'), new OA\Property(property: 'email', type: 'string', format: 'email', example: 'jane@example.com'), new OA\Property(property: 'password', type: 'string', format: 'password', minLength: 8, example: 'secure-password'), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password', example: 'secure-password')], type: 'object')]
#[OA\Schema(schema: 'LoginRequest', required: ['email', 'password', 'device_name'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email', example: 'admin@example.com'), new OA\Property(property: 'password', type: 'string', format: 'password', example: 'secure-password'), new OA\Property(property: 'device_name', type: 'string', example: 'Swagger UI')], type: 'object')]
#[OA\Schema(schema: 'ProfileRequest', required: ['name'], properties: [new OA\Property(property: 'name', type: 'string', example: 'Jane Doe')], type: 'object')]
#[OA\Schema(schema: 'ChangePasswordRequest', required: ['current_password', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'current_password', type: 'string', format: 'password'), new OA\Property(property: 'password', type: 'string', format: 'password', minLength: 8), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password')], type: 'object')]
#[OA\Schema(schema: 'EmailRequest', required: ['email'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email', example: 'user@example.com')], type: 'object')]
#[OA\Schema(schema: 'ResetPasswordRequest', required: ['token', 'email', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'token', type: 'string'), new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'password', type: 'string', format: 'password', minLength: 12), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password')], type: 'object')]
#[OA\Schema(schema: 'RoleRequest', properties: [new OA\Property(property: 'name', type: 'string', pattern: '^[a-z0-9-]+$', example: 'editor'), new OA\Property(property: 'permissions', type: 'array', items: new OA\Items(type: 'string'), example: ['users.view', 'settings.view'])], type: 'object')]
#[OA\Schema(schema: 'RoleUpdateRequest', required: ['updated_at'], properties: [new OA\Property(property: 'updated_at', description: 'Current updated_at value used to prevent overwriting another administrator change.', type: 'string', format: 'date-time'), new OA\Property(property: 'name', type: 'string', pattern: '^[a-z0-9-]+$', example: 'editor'), new OA\Property(property: 'permissions', type: 'array', items: new OA\Items(type: 'string'), example: ['users.view', 'settings.view'])], type: 'object')]
#[OA\Schema(schema: 'AdminCreateUserRequest', required: ['name', 'email', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'name', type: 'string', example: 'Operator'), new OA\Property(property: 'email', type: 'string', format: 'email', example: 'operator@example.com'), new OA\Property(property: 'password', type: 'string', format: 'password', minLength: 8, example: 'secure-password'), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password', example: 'secure-password'), new OA\Property(property: 'status', type: 'string', enum: ['active', 'suspended'], example: 'active'), new OA\Property(property: 'roles', type: 'array', items: new OA\Items(type: 'string'), example: ['user'])], type: 'object')]
#[OA\Schema(schema: 'UserStatusRequest', required: ['status'], properties: [new OA\Property(property: 'status', type: 'string', enum: ['active', 'suspended'], example: 'active')], type: 'object')]
#[OA\Schema(schema: 'UserRolesRequest', required: ['roles'], properties: [new OA\Property(property: 'roles', type: 'array', items: new OA\Items(type: 'string'), example: ['admin', 'user'])], type: 'object')]
#[OA\Schema(schema: 'SettingsRequest', required: ['settings'], properties: [new OA\Property(property: 'settings', properties: [new OA\Property(property: 'app.name', type: 'string', example: 'My Platform'), new OA\Property(property: 'auth.registration_enabled', type: 'boolean', example: false), new OA\Property(property: 'auth.token_expiration_days', type: 'integer', example: 30)], type: 'object')], type: 'object')]
final class RequestSchemas {}
