<?php

namespace Core\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'UserProfile', required: ['id', 'name', 'email', 'status', 'roles', 'permissions'], properties: [new OA\Property(property: 'id', type: 'integer', example: 1), new OA\Property(property: 'name', type: 'string', example: 'Administrator'), new OA\Property(property: 'email', type: 'string', format: 'email', example: 'admin@example.com'), new OA\Property(property: 'status', type: 'string', enum: ['active', 'suspended'], example: 'active'), new OA\Property(property: 'email_verified_at', type: ['string', 'null'], format: 'date-time', example: '2026-09-21T10:34:08Z'), new OA\Property(property: 'last_login_at', type: ['string', 'null'], format: 'date-time', example: '2026-09-21T10:40:00Z'), new OA\Property(property: 'roles', type: 'array', items: new OA\Items(type: 'string'), example: ['super-admin']), new OA\Property(property: 'permissions', type: 'array', items: new OA\Items(type: 'string'), example: ['users.view', 'roles.view', 'settings.update'])], type: 'object')]
#[OA\Schema(schema: 'LoginSuccessResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', required: ['token', 'token_type', 'expires_at', 'user'], properties: [new OA\Property(property: 'token', type: 'string', example: '1|sanctum-plain-text-token'), new OA\Property(property: 'token_type', type: 'string', example: 'Bearer'), new OA\Property(property: 'expires_at', type: 'string', format: 'date-time', example: '2026-10-21T10:40:00Z'), new OA\Property(property: 'user', ref: '#/components/schemas/UserProfile')], type: 'object')], type: 'object')]
#[OA\Schema(schema: 'UserSuccessResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', ref: '#/components/schemas/UserProfile')], type: 'object')]
#[OA\Schema(schema: 'MessageSuccessResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', required: ['message'], properties: [new OA\Property(property: 'message', type: 'string', example: 'Operation completed successfully.')], type: 'object')], type: 'object')]
#[OA\Schema(schema: 'ErrorResponse', required: ['success', 'message', 'errors'], properties: [new OA\Property(property: 'success', type: 'boolean', example: false), new OA\Property(property: 'message', type: 'string', example: 'Email address is not verified.'), new OA\Property(property: 'errors', type: 'object', example: [])], type: 'object')]
#[OA\Schema(schema: 'ValidationErrorResponse', required: ['success', 'message', 'errors'], properties: [new OA\Property(property: 'success', type: 'boolean', example: false), new OA\Property(property: 'message', type: 'string', example: 'Validation failed'), new OA\Property(property: 'errors', properties: [new OA\Property(property: 'email', type: 'array', items: new OA\Items(type: 'string'), example: ['The email field must be a valid email address.'])], type: 'object')], type: 'object')]
#[OA\Schema(schema: 'CursorPaginationMeta', required: ['path', 'per_page', 'next_cursor', 'next_page_url', 'prev_cursor', 'prev_page_url'], properties: [new OA\Property(property: 'path', type: 'string', example: 'https://core-r.p85.test:8443/api/users'), new OA\Property(property: 'per_page', type: 'integer', example: 20), new OA\Property(property: 'next_cursor', type: ['string', 'null'], example: 'eyJuYW1lIjoiSmFuZSJ9'), new OA\Property(property: 'next_page_url', type: ['string', 'null']), new OA\Property(property: 'prev_cursor', type: ['string', 'null']), new OA\Property(property: 'prev_page_url', type: ['string', 'null'])], type: 'object')]
#[OA\Schema(schema: 'UsersCursorResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', required: ['data', 'path', 'per_page'], properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/UserProfile')), new OA\Property(property: 'path', type: 'string', example: 'https://core-r.p85.test:8443/api/users'), new OA\Property(property: 'per_page', type: 'integer', example: 20), new OA\Property(property: 'next_cursor', type: ['string', 'null'], example: 'eyJuYW1lIjoiSmFuZSJ9'), new OA\Property(property: 'next_page_url', type: ['string', 'null']), new OA\Property(property: 'prev_cursor', type: ['string', 'null']), new OA\Property(property: 'prev_page_url', type: ['string', 'null'])], type: 'object')], type: 'object')]
#[OA\Schema(schema: 'ApiToken', required: ['id', 'name', 'is_current'], properties: [new OA\Property(property: 'id', type: 'integer', example: 12), new OA\Property(property: 'name', type: 'string', example: 'Chrome on laptop'), new OA\Property(property: 'last_used_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'expires_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'created_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'is_current', type: 'boolean', example: true)], type: 'object')]
#[OA\Schema(schema: 'TokensSuccessResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/ApiToken'))], type: 'object')]
#[OA\Schema(schema: 'AuditCursorResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', description: 'Cursor paginator containing audit event records.', type: 'object')], type: 'object')]
#[OA\Schema(schema: 'SettingsMetadataResponse', required: ['success', 'data'], properties: [new OA\Property(property: 'success', type: 'boolean', example: true), new OA\Property(property: 'data', type: 'array', items: new OA\Items(properties: [new OA\Property(property: 'key', type: 'string', example: 'auth.registration_enabled'), new OA\Property(property: 'value', type: 'boolean', example: true), new OA\Property(property: 'type', type: 'string', example: 'boolean'), new OA\Property(property: 'default', type: 'boolean', example: false), new OA\Property(property: 'rules', type: 'array', items: new OA\Items(type: 'string')), new OA\Property(property: 'public', type: 'boolean'), new OA\Property(property: 'editable', type: 'boolean'), new OA\Property(property: 'description', type: 'string')], type: 'object'))], type: 'object')]
final class ResponseSchemas {}
