<?php

namespace Modules\Settings;

class SettingsRegistry
{
    public const DEFINITIONS = [
        'app.name' => ['group' => 'application', 'type' => 'string', 'default' => 'Core R', 'fallback' => 'runtime-settings.app_name', 'rules' => ['string', 'max:100'], 'public' => true, 'editable' => true, 'description' => 'settings.app_name'],
        'app.locale' => ['group' => 'application', 'type' => 'string', 'default' => 'en', 'fallback' => 'runtime-settings.app_locale', 'rules' => ['string', 'max:10'], 'public' => true, 'editable' => true, 'description' => 'settings.app_locale'],
        'app.timezone' => ['group' => 'application', 'type' => 'string', 'default' => 'Asia/Jakarta', 'fallback' => 'runtime-settings.app_timezone', 'rules' => ['string', 'timezone'], 'public' => true, 'editable' => true, 'description' => 'settings.app_timezone'],
        'auth.registration_enabled' => ['group' => 'authentication', 'type' => 'boolean', 'default' => false, 'fallback' => 'runtime-settings.registration_enabled', 'rules' => ['boolean'], 'public' => true, 'editable' => true, 'description' => 'settings.registration_enabled'],
        'auth.email_verification_required' => ['group' => 'authentication', 'type' => 'boolean', 'default' => true, 'fallback' => 'runtime-settings.email_verification_required', 'rules' => ['boolean'], 'public' => true, 'editable' => true, 'description' => 'settings.email_verification_required'],
        'auth.token_expiration_days' => ['group' => 'authentication', 'type' => 'integer', 'default' => 30, 'fallback' => 'runtime-settings.token_expiration_days', 'rules' => ['integer', 'min:1', 'max:365'], 'public' => false, 'editable' => true, 'description' => 'settings.token_expiration_days'],
        'auth.max_login_attempts' => ['group' => 'authentication', 'type' => 'integer', 'default' => 5, 'fallback' => 'runtime-settings.max_login_attempts', 'rules' => ['integer', 'min:1', 'max:20'], 'public' => false, 'editable' => true, 'description' => 'settings.max_login_attempts'],
        'files.max_upload_mb' => ['group' => 'files', 'type' => 'integer', 'default' => 10, 'fallback' => 'runtime-settings.max_upload_mb', 'rules' => ['integer', 'min:1', 'max:100'], 'public' => false, 'editable' => true, 'description' => 'settings.max_upload_mb'],
        'files.allowed_mime_types' => ['group' => 'files', 'type' => 'array', 'default' => ['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'text/plain', 'text/csv', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], 'fallback' => 'runtime-settings.allowed_mime_types', 'rules' => ['array', 'min:1', 'max:15'], 'public' => false, 'editable' => true, 'description' => 'settings.allowed_mime_types'],
        'realtime.event_retention_days' => ['group' => 'realtime', 'type' => 'integer', 'default' => 7, 'fallback' => 'runtime-settings.event_retention_days', 'rules' => ['integer', 'min:1', 'max:90'], 'public' => false, 'editable' => true, 'description' => 'settings.event_retention_days'],
        'ops.failed_job_retention_hours' => ['group' => 'operations', 'type' => 'integer', 'default' => 168, 'fallback' => 'runtime-settings.failed_job_retention_hours', 'rules' => ['integer', 'min:1', 'max:2160'], 'public' => false, 'editable' => true, 'description' => 'settings.failed_job_retention_hours'],
        'data_transfers.retention_days' => ['group' => 'operations', 'type' => 'integer', 'default' => 30, 'fallback' => 'runtime-settings.data_transfer_retention_days', 'rules' => ['integer', 'min:1', 'max:365'], 'public' => false, 'editable' => true, 'description' => 'settings.data_transfer_retention_days'],
        'api.idempotency_ttl_hours' => ['group' => 'api', 'type' => 'integer', 'default' => 24, 'fallback' => 'runtime-settings.idempotency_ttl_hours', 'rules' => ['integer', 'min:1', 'max:168'], 'public' => false, 'editable' => true, 'description' => 'settings.idempotency_ttl_hours'],
        'rate_limit.auth_register' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 5, 'fallback' => 'runtime-settings.rate_limits.auth_register', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_auth_register'],
        'rate_limit.auth_login' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 20, 'fallback' => 'runtime-settings.rate_limits.auth_login', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_auth_login'],
        'rate_limit.auth_recovery' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 3, 'fallback' => 'runtime-settings.rate_limits.auth_recovery', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_auth_recovery'],
        'rate_limit.files_upload' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 20, 'fallback' => 'runtime-settings.rate_limits.files_upload', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_files_upload'],
        'rate_limit.events_poll' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 120, 'fallback' => 'runtime-settings.rate_limits.events_poll', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_events_poll'],
        'rate_limit.notifications_mutate' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 60, 'fallback' => 'runtime-settings.rate_limits.notifications_mutate', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_notifications_mutate'],
        'rate_limit.admin_sensitive' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 30, 'fallback' => 'runtime-settings.rate_limits.admin_sensitive', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_admin_sensitive'],
        'rate_limit.payment_webhooks' => ['group' => 'rate_limits', 'type' => 'integer', 'default' => 120, 'fallback' => 'runtime-settings.rate_limits.payment_webhooks', 'rules' => ['integer', 'min:1', 'max:10000'], 'public' => false, 'editable' => true, 'description' => 'settings.rate_limit_payment_webhooks'],
        'payments.midtrans_enabled' => ['group' => 'payments', 'type' => 'boolean', 'default' => false, 'fallback' => 'runtime-settings.midtrans_enabled', 'rules' => ['boolean'], 'public' => false, 'editable' => true, 'description' => 'settings.midtrans_enabled'],
        'payments.midtrans_timeout' => ['group' => 'payments', 'type' => 'integer', 'default' => 10, 'fallback' => 'runtime-settings.midtrans_timeout', 'rules' => ['integer', 'min:1', 'max:60'], 'public' => false, 'editable' => true, 'description' => 'settings.midtrans_timeout'],
    ];
}
