name: rukun

services:
  rukun-reverb:
    image: docker-php85
    working_dir: /var/www/p85/rukun
    volumes:
      - ./:/var/www/p85/rukun
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true
    name: docker-network
