<?php

namespace Modules\Engagement\OpenApi;

use OpenApi\Attributes as OA;

// ── Schemas ───────────────────────────────────────────────────────────────────

#[OA\Schema(schema: 'EngagementDocument', type: 'object', properties: [new OA\Property(property: 'file_id', type: 'string', format: 'uuid')])]
#[OA\Schema(schema: 'PatrolTeam', type: 'object', properties: [new OA\Property(property: 'public_id', type: 'string', format: 'uuid'), new OA\Property(property: 'area_id', type: 'string', format: 'uuid'), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'created_at', type: 'string', format: 'date-time')])]
#[OA\Schema(schema: 'TeamMember', type: 'object', properties: [new OA\Property(property: 'user_id', type: 'string', format: 'uuid'), new OA\Property(property: 'household_id', type: 'string', format: 'uuid')])]
#[OA\Schema(schema: 'PatrolPolicy', type: 'object', properties: [new OA\Property(property: 'area_id', type: 'string', format: 'uuid'), new OA\Property(property: 'payment_type_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'due_days', type: 'integer', minimum: 1, maximum: 90), new OA\Property(property: 'updated_at', type: ['string', 'null'], format: 'date-time')])]
#[OA\Schema(schema: 'CommunityEvent', type: 'object', properties: [new OA\Property(property: 'public_id', type: 'string', format: 'uuid'), new OA\Property(property: 'kind', type: 'string', enum: ['patrol', 'activity']), new OA\Property(property: 'area_id', type: 'string', format: 'uuid'), new OA\Property(property: 'team_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'title', type: 'string'), new OA\Property(property: 'notes', type: ['string', 'null']), new OA\Property(property: 'starts_at', type: 'string', format: 'date-time'), new OA\Property(property: 'ends_at', type: 'string', format: 'date-time'), new OA\Property(property: 'status', type: 'string', enum: ['scheduled', 'cancelled']), new OA\Property(property: 'fee_amount', type: ['integer', 'null']), new OA\Property(property: 'due_days', type: ['integer', 'null']), new OA\Property(property: 'version', type: 'integer'), new OA\Property(property: 'documents', type: 'array', items: new OA\Items(ref: '#/components/schemas/EngagementDocument')), new OA\Property(property: 'created_at', type: 'string', format: 'date-time')])]
#[OA\Schema(schema: 'Participant', type: 'object', properties: [new OA\Property(property: 'billing', type: ['object', 'null'], properties: [new OA\Property(property: 'amount', type: 'integer'), new OA\Property(property: 'paid_amount', type: 'integer'), new OA\Property(property: 'outstanding_amount', type: 'integer'), new OA\Property(property: 'status', type: 'string'), new OA\Property(property: 'overdue', type: 'boolean')]), new OA\Property(property: 'event_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'leave_recorded_by', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'leave_reviewed_by', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'attendance_by', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'leave_review_note', type: ['string', 'null']), new OA\Property(property: 'public_id', type: 'string', format: 'uuid'), new OA\Property(property: 'user_id', type: 'string', format: 'uuid'), new OA\Property(property: 'household_id', type: 'string', format: 'uuid'), new OA\Property(property: 'status', type: 'string', enum: ['active', 'withdrawn']), new OA\Property(property: 'attendance', type: 'string', enum: ['pending', 'present', 'absent', 'excused']), new OA\Property(property: 'attendance_note', type: ['string', 'null']), new OA\Property(property: 'attendance_at', type: ['string', 'null'], format: 'date-time'), new OA\Property(property: 'leave_status', type: 'string', enum: ['none', 'pending', 'approved', 'rejected']), new OA\Property(property: 'leave_reason', type: ['string', 'null']), new OA\Property(property: 'waived', type: 'boolean'), new OA\Property(property: 'invoice_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'version', type: 'integer')])]
#[OA\Schema(schema: 'ParticipantHistory', type: 'object', properties: [new OA\Property(property: 'public_id', type: 'string', format: 'uuid'), new OA\Property(property: 'actor_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'action', type: 'string', enum: ['assigned', 'attendance', 'leave', 'approve_leave', 'reject_leave', 'charge', 'withdraw']), new OA\Property(property: 'version', type: 'integer'), new OA\Property(property: 'created_at', type: 'string', format: 'date-time')])]
#[OA\Schema(schema: 'Incident', type: 'object', properties: [new OA\Property(property: 'public_id', type: 'string', format: 'uuid'), new OA\Property(property: 'event_id', type: 'string', format: 'uuid'), new OA\Property(property: 'reported_by', type: 'string', format: 'uuid'), new OA\Property(property: 'description', type: 'string'), new OA\Property(property: 'documents', type: 'array', items: new OA\Items(ref: '#/components/schemas/EngagementDocument')), new OA\Property(property: 'created_at', type: 'string', format: 'date-time')])]

// ── Request schemas ───────────────────────────────────────────────────────────

#[OA\Schema(schema: 'CreateTeamInput', type: 'object', required: ['area_id', 'name'], properties: [new OA\Property(property: 'area_id', type: 'string', format: 'uuid'), new OA\Property(property: 'name', type: 'string', maxLength: 120)])]
#[OA\Schema(schema: 'TeamMemberInput', type: 'object', required: ['user_id'], properties: [new OA\Property(property: 'user_id', type: 'string', format: 'uuid'), new OA\Property(property: 'household_id', type: 'string', format: 'uuid'), new OA\Property(property: 'remove', type: 'boolean', default: false, description: 'Set true to remove the member')])]
#[OA\Schema(schema: 'SetPolicyInput', type: 'object', required: ['area_id', 'due_days'], properties: [new OA\Property(property: 'area_id', type: 'string', format: 'uuid'), new OA\Property(property: 'payment_type_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'due_days', type: 'integer', minimum: 1, maximum: 90)])]
#[OA\Schema(schema: 'CreateEventInput', type: 'object', required: ['kind', 'area_id', 'title', 'starts_at', 'ends_at'], properties: [new OA\Property(property: 'kind', type: 'string', enum: ['patrol', 'activity']), new OA\Property(property: 'area_id', type: 'string', format: 'uuid'), new OA\Property(property: 'team_id', type: ['string', 'null'], format: 'uuid', description: 'Required when kind=patrol, prohibited when kind=activity'), new OA\Property(property: 'title', type: 'string', maxLength: 200), new OA\Property(property: 'notes', type: ['string', 'null'], maxLength: 5000), new OA\Property(property: 'starts_at', type: 'string', format: 'date-time'), new OA\Property(property: 'ends_at', type: 'string', format: 'date-time', description: 'Must be after starts_at'), new OA\Property(property: 'due_days', type: 'integer', minimum: 1, maximum: 90), new OA\Property(property: 'payment_type_id', type: ['string', 'null'], format: 'uuid'), new OA\Property(property: 'attachments', type: 'array', maxItems: 10, items: new OA\Items(type: 'string', format: 'uuid'))])]
#[OA\Schema(schema: 'CancelEventInput', type: 'object', required: ['version', 'reason'], properties: [new OA\Property(property: 'version', type: 'integer', minimum: 1), new OA\Property(property: 'reason', type: 'string', maxLength: 2000)])]
#[OA\Schema(schema: 'ParticipateInput', type: 'object', required: ['household_id'], properties: [new OA\Property(property: 'household_id', type: 'string', format: 'uuid'), new OA\Property(property: 'user_id', type: ['string', 'null'], format: 'uuid')])]
#[OA\Schema(schema: 'ParticipantActionInput', type: 'object', required: ['action', 'version'], properties: [new OA\Property(property: 'action', type: 'string', enum: ['attendance', 'leave', 'approve_leave', 'reject_leave', 'charge', 'withdraw']), new OA\Property(property: 'version', type: 'integer', minimum: 1), new OA\Property(property: 'attendance', type: 'string', enum: ['present', 'absent'], description: 'Required when action=attendance; excused is set only by leave approval'), new OA\Property(property: 'note', type: ['string', 'null'], maxLength: 2000, description: 'Required for leave, reject_leave, and approval with waive=true'), new OA\Property(property: 'waive', type: 'boolean', description: 'Only valid when action=approve_leave')])]
#[OA\Schema(schema: 'CreateIncidentInput', type: 'object', required: ['description'], properties: [new OA\Property(property: 'description', type: 'string', maxLength: 5000), new OA\Property(property: 'attachments', type: 'array', maxItems: 10, items: new OA\Items(type: 'string', format: 'uuid'))])]

// ── Response schemas ──────────────────────────────────────────────────────────

#[OA\Schema(schema: 'PatrolTeamResponse', type: 'object', example: ['success' => true, 'data' => ['public_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'area_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'name' => 'Tim Ronda Malam A', 'created_at' => '2026-10-07T17:00:00Z']])]
#[OA\Schema(schema: 'PatrolTeamPage', type: 'object', example: ['success' => true, 'data' => ['data' => [['public_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'area_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'name' => 'Tim Ronda Malam A', 'created_at' => '2026-10-07T17:00:00Z']], 'path' => 'https://rukun.p85.test/api/engagement/teams', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]
#[OA\Schema(schema: 'TeamMemberPage', type: 'object', example: ['success' => true, 'data' => ['data' => [['user_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'household_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9']], 'path' => 'https://rukun.p85.test/api/engagement/teams/UUID/members', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]
#[OA\Schema(schema: 'PatrolPolicyResponse', type: 'object', example: ['success' => true, 'data' => ['area_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'payment_type_id' => null, 'due_days' => 14, 'updated_at' => '2026-10-07T17:00:00Z']])]
#[OA\Schema(schema: 'CommunityEventResponse', type: 'object', example: ['success' => true, 'data' => ['public_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'kind' => 'patrol', 'area_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'team_id' => '01994f65-07c8-73f7-b61d-140b489cfeba', 'title' => 'Ronda Malam Minggu', 'notes' => null, 'starts_at' => '2026-10-10T13:00:00Z', 'ends_at' => '2026-10-10T19:00:00Z', 'status' => 'scheduled', 'fee_amount' => null, 'due_days' => 14, 'version' => 1, 'documents' => [], 'created_at' => '2026-10-07T17:00:00Z']])]
#[OA\Schema(schema: 'CommunityEventPage', type: 'object', example: ['success' => true, 'data' => ['data' => [], 'path' => 'https://rukun.p85.test/api/engagement/events', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]
#[OA\Schema(schema: 'ParticipantResponse', type: 'object', example: ['success' => true, 'data' => ['public_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'user_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'household_id' => '01994f65-07c8-73f7-b61d-140b489cfeba', 'status' => 'active', 'attendance' => 'pending', 'attendance_note' => null, 'attendance_at' => null, 'leave_status' => 'none', 'leave_reason' => null, 'waived' => null, 'invoice_id' => null, 'version' => 1]])]
#[OA\Schema(schema: 'ParticipantPage', type: 'object', example: ['success' => true, 'data' => ['data' => [], 'path' => 'https://rukun.p85.test/api/engagement/events/UUID/participants', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]
#[OA\Schema(schema: 'ParticipantHistoryPage', type: 'object', example: ['success' => true, 'data' => ['data' => [['public_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'actor_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'action' => 'leave', 'version' => 2, 'created_at' => '2026-10-07T17:00:00Z']], 'path' => 'https://rukun.p85.test/api/engagement/events/UUID/participants/UUID/history', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]
#[OA\Schema(schema: 'IncidentResponse', type: 'object', example: ['success' => true, 'data' => ['public_id' => '01994f65-07c8-73f7-b61d-140b489cfeb8', 'event_id' => '01994f65-07c8-73f7-b61d-140b489cfeb9', 'reported_by' => '01994f65-07c8-73f7-b61d-140b489cfeba', 'description' => 'Kabel listrik putus di depan RT 03 no 12.', 'documents' => [], 'created_at' => '2026-10-07T17:00:00Z']])]
#[OA\Schema(schema: 'IncidentPage', type: 'object', example: ['success' => true, 'data' => ['data' => [], 'path' => 'https://rukun.p85.test/api/engagement/events/UUID/incidents', 'per_page' => 20, 'next_cursor' => null, 'next_page_url' => null, 'prev_cursor' => null, 'prev_page_url' => null]])]

// ── Endpoints — Teams ─────────────────────────────────────────────────────────

#[OA\Get(path: '/api/engagement/teams', operationId: 'engagementTeams', summary: 'List patrol teams scoped to authenticated user RT/RW', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20)), new OA\Parameter(name: 'area_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/PatrolTeamPage')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/teams', operationId: 'engagementCreateTeam', summary: 'Create a patrol team', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreateTeamInput')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/PatrolTeamResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Get(path: '/api/engagement/teams/{team}/members', operationId: 'engagementTeamMembers', summary: 'List members of a patrol team', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20)), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/TeamMemberPage')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Team not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/teams/{team}/members', operationId: 'engagementUpdateTeamMember', summary: 'Add or remove a member from a patrol team; set remove=true to remove', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/TeamMemberInput')), responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'success', type: 'boolean'), new OA\Property(property: 'data', type: 'object', properties: [new OA\Property(property: 'public_id', type: 'string', format: 'uuid')])])), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Team not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]

// ── Endpoints — Patrol Policy ─────────────────────────────────────────────────

#[OA\Get(path: '/api/engagement/patrol-policy/{area}', operationId: 'engagementGetPolicy', summary: 'Read patrol policy for an area; returns null data if not yet configured', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'area', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Success (data may be null)', content: new OA\JsonContent(ref: '#/components/schemas/PatrolPolicyResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Area not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/patrol-policy', operationId: 'engagementSetPolicy', summary: 'Set or update patrol policy for an area', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/SetPolicyInput')), responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/PatrolPolicyResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]

// ── Endpoints — Events ────────────────────────────────────────────────────────

#[OA\Get(path: '/api/engagement/events', operationId: 'engagementEvents', summary: 'List community events scoped to user area', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20)), new OA\Parameter(name: 'kind', in: 'query', schema: new OA\Schema(type: 'string', enum: ['patrol', 'activity'])), new OA\Parameter(name: 'area_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['scheduled', 'cancelled'])), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/CommunityEventPage')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Get(path: '/api/engagement/events/{id}', operationId: 'engagementShowEvent', summary: 'Show a single event; includes version required for cancel', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/CommunityEventResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/events', operationId: 'engagementCreateEvent', summary: 'Create patrol or activity event; team_id required for patrol, prohibited for activity', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreateEventInput')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/CommunityEventResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/events/{id}/cancel', operationId: 'engagementCancelEvent', summary: 'Cancel a scheduled event; 409 if version mismatch or active invoices exist', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CancelEventInput')), responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/CommunityEventResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Stale version or active invoices', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]

// ── Endpoints — Participants ──────────────────────────────────────────────────

#[OA\Get(path: '/api/engagement/events/{id}/participants', operationId: 'engagementParticipants', summary: 'List participants; filter by status active|withdrawn', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20)), new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['active', 'withdrawn'])), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/ParticipantPage')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Event not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/events/{id}/participants', operationId: 'engagementEnrollParticipant', summary: 'Officer enrolls a resident; household_id required, user_id optional', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/ParticipateInput')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ParticipantResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Event not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency or duplicate conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/events/{id}/join', operationId: 'engagementJoin', summary: 'Resident self-registers to join an event', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/ParticipateInput')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ParticipantResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Event not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency or duplicate conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/events/{eventId}/participants/{participantId}/actions', operationId: 'engagementParticipantAction', summary: 'Apply versioned action: attendance, leave, approve_leave, reject_leave, charge, withdraw', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'eventId', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'participantId', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/ParticipantActionInput')), responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/ParticipantResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Stale version, lifecycle or idempotency conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Get(path: '/api/engagement/events/{eventId}/participants/{participantId}/history', operationId: 'engagementParticipantHistory', summary: 'Immutable chronological action history for a participant', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'eventId', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'participantId', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20)), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/ParticipantHistoryPage')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]

// ── Endpoints — Incidents ─────────────────────────────────────────────────────

#[OA\Get(path: '/api/engagement/events/{id}/incidents', operationId: 'engagementIncidents', summary: 'List incidents; managers see all, residents see own only', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20)), new OA\Parameter(name: 'cursor', in: 'query', schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(ref: '#/components/schemas/IncidentPage')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Event not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
#[OA\Post(path: '/api/engagement/events/{id}/incidents', operationId: 'engagementCreateIncident', summary: 'Record an incident; active participants may report', security: [['bearerAuth' => []]], tags: ['Engagement'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'Idempotency-Key', in: 'header', required: true, schema: new OA\Schema(type: 'string', minLength: 8, maxLength: 128))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreateIncidentInput')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/IncidentResponse')), new OA\Response(response: 401, description: 'Unauthenticated', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 403, description: 'Authority denied', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 404, description: 'Event not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 409, description: 'Idempotency conflict', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse')), new OA\Response(response: 429, description: 'Rate limited', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))])]
class EngagementSpec {}
